import { StyleSheet } from 'react-native';

// 흰 바탕·여백·글자 크기로 위계를 만들고 코럴은 주 행동에만 사용한다.
export const homeStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  content: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 28,
    maxWidth: 640,
    width: '100%',
    alignSelf: 'center',
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 44,
  },
  logo: { width: 154, height: 48 },
  login: { minHeight: 44, justifyContent: 'center', paddingLeft: 14 },
  welcome: { gap: 18, paddingTop: 8 },
  eyebrow: { fontSize: 12, color: '#9A4E3E', letterSpacing: 0.4 },
  headline: {
    fontSize: 30,
    lineHeight: 41,
    letterSpacing: -1,
    fontWeight: '700',
    color: '#203247',
  },
  welcomeBottom: { flexDirection: 'row', alignItems: 'center', minHeight: 150 },
  welcomeCopy: { flex: 1, gap: 10 },
  welcomeTitle: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    color: '#203247',
  },
  haru: { width: 118, height: 148 },
  supporting: { fontSize: 13, lineHeight: 21, color: '#697581', flexShrink: 1 },
  startButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: '#C84432',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    gap: 12,
  },
  startText: {
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '600',
    color: '#FFFFFF',
    flexShrink: 1,
  },
  secondaryButton: { backgroundColor: '#F5F6F7' },
  secondaryText: { color: '#203247' },
  pressed: { opacity: 0.78 },
  section: { gap: 10 },
  sectionTitle: {
    fontSize: 19,
    lineHeight: 27,
    fontWeight: '700',
    color: '#203247',
    letterSpacing: -0.4,
  },
  destinations: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  destination: {
    flexGrow: 1,
    flexBasis: '20%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    minHeight: 48,
    paddingHorizontal: 8,
    paddingVertical: 12,
    backgroundColor: '#F5F6F7',
    borderRadius: 10,
  },
  destinationText: { fontSize: 14, fontWeight: '600', color: '#203247' },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF0F2',
    minHeight: 72,
  },
  linkCopy: { flex: 1, gap: 4 },
  linkText: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    color: '#203247',
  },
  community: {
    backgroundColor: '#F9F3EB',
    borderRadius: 14,
    padding: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  communityCopy: { flex: 1, gap: 12 },
  communityEyebrow: { fontSize: 12, color: '#8D5C40', fontWeight: '600' },
  communityTitle: {
    fontSize: 20,
    lineHeight: 29,
    letterSpacing: -0.5,
    fontWeight: '600',
    color: '#203247',
  },
  tripTicket: {
    padding: 22,
    backgroundColor: '#F7F8FA',
    borderRadius: 12,
    gap: 12,
  },
  ticketTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ticketStatus: { color: '#A93C2D', fontSize: 12, fontWeight: '600' },
  ticketCity: {
    color: '#203247',
    fontSize: 24,
    lineHeight: 42,
    fontWeight: '700',
    letterSpacing: -0.8,
  },
  ticketTitle: { color: '#405163', fontSize: 15, lineHeight: 23 },
  ticketFooter: {
    borderTopWidth: 1,
    borderTopColor: '#E2E7EC',
    marginTop: 6,
    paddingTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  ticketDate: { color: '#697581', fontSize: 12, lineHeight: 20, flexShrink: 1 },
});
