/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api/wrangler.jsonc --include-runtime=false --strict-vars=false apps/api/worker-configuration.d.ts` (hash: de105b5dc831130d27f79f9feb8ccfa0)
interface __BaseEnv_Env {
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  ALLOWED_ORIGINS: string;
  GOOGLE_VISION_API_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface StagingEnv {
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
  }
  interface ProductionEnv {
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
    GOOGLE_VISION_API_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'SUPABASE_URL'
      | 'SUPABASE_ANON_KEY'
      | 'ALLOWED_ORIGINS'
      | 'GOOGLE_VISION_API_KEY'
    >
  > {}
}
