/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api/wrangler.jsonc --include-runtime=false --strict-vars=false apps/api/worker-configuration.d.ts` (hash: e08515db3df71b9f85e675a3d116472e)
interface __BaseEnv_Env {
  MEDIA?: R2Bucket;
  DB?: D1Database;
  AI?: Ai;
  SUPABASE_URL: string;
  AUTH_BASE_URL: string;
  SUPABASE_ANON_KEY: string;
  ALLOWED_ORIGINS: string;
  AUTH_SECRET?: string;
  GOOGLE_VISION_API_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface StagingEnv {
    MEDIA: R2Bucket;
    DB: D1Database;
    AI: Ai;
    SUPABASE_URL: string;
    AUTH_BASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
    AUTH_SECRET: string;
  }
  interface ProductionEnv {
    SUPABASE_URL: string;
    AUTH_BASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
    GOOGLE_VISION_API_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'SUPABASE_URL'
      | 'AUTH_BASE_URL'
      | 'SUPABASE_ANON_KEY'
      | 'ALLOWED_ORIGINS'
      | 'AUTH_SECRET'
      | 'GOOGLE_VISION_API_KEY'
    >
  > {}
}
