/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 0b2cf040473a75a8ad9d93d2c8974d23)
interface __BaseEnv_Env {
  MEDIA?: R2Bucket;
  DB?: D1Database;
  AI?: Ai;
  GOOGLE_CLIENT_ID: string;
  KAKAO_CLIENT_ID: string;
  NAVER_CLIENT_ID: string;
  SUPABASE_URL: string;
  AUTH_BASE_URL: string;
  SUPABASE_ANON_KEY: string;
  ALLOWED_ORIGINS: string;
  AUTH_SECRET?: string;
  GOOGLE_VISION_API_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface StagingEnv {
    MEDIA: R2Bucket;
    DB: D1Database;
    AI: Ai;
    GOOGLE_CLIENT_ID: string;
    KAKAO_CLIENT_ID: string;
    NAVER_CLIENT_ID: string;
    SUPABASE_URL: string;
    AUTH_BASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
    AUTH_SECRET: string;
  }
  interface ProductionEnv {
    GOOGLE_CLIENT_ID: string;
    KAKAO_CLIENT_ID: string;
    NAVER_CLIENT_ID: string;
    SUPABASE_URL: string;
    AUTH_BASE_URL: string;
    SUPABASE_ANON_KEY: string;
    ALLOWED_ORIGINS: string;
    GOOGLE_VISION_API_KEY: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'GOOGLE_CLIENT_ID'
      | 'KAKAO_CLIENT_ID'
      | 'NAVER_CLIENT_ID'
      | 'SUPABASE_URL'
      | 'AUTH_BASE_URL'
      | 'SUPABASE_ANON_KEY'
      | 'ALLOWED_ORIGINS'
      | 'AUTH_SECRET'
      | 'GOOGLE_VISION_API_KEY'
    >
  > {}
}
